[package]
name = "pdb_split"
version = "0.1.0"
authors = ["shima <shima.kazuhide0705@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpdb = {path = "../libpdb/"}
anyhow = "1.0"